name: CI
on:
  push:
    paths-ignore:
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
      - "docs/**"
      - "**.md"
      - "**.txt"
      - "!CMakeLists.txt"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**.txt"
      - "!CMakeLists.txt"
      - "LICENSE"
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        baulk_target: [baulk-win64, baulk-win32, baulk-arm64]
        include:
          - baulk_target: baulk-win64
            msvc_arch: amd64
          - baulk_target: baulk-win32
            msvc_arch: amd64_x86
          - baulk_target: baulk-arm64
            msvc_arch: amd64_arm64
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: compile-baulk
        shell: cmd
        env:
          msvc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %msvc_arch%
          set BAULK_REFNAME=${{ github.ref }}
          mkdir build
          cd build
          set CC=cl
          set CXX=cl
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
          ninja all

      - name: Package Release
        if: startsWith(github.ref, 'refs/tags/')
        shell: cmd
        env:
          msvc_arch: ${{ matrix.msvc_arch }}
        # create package and show sha256 hash
        run: pwsh -NoProfile -NoLogo -ExecutionPolicy unrestricted -File "./script/package.ps1"
      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file_glob: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/Baulk-*.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload Setup
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file_glob: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/BaulkSetup*.exe
          tag: ${{ github.ref }}
          overwrite: true
