name: BaulkCI
on:
  push:
    paths-ignore:
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
      - "docs/**"
      - "**.md"
      - "**.txt"
      - "!CMakeLists.txt"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**.txt"
      - "!CMakeLists.txt"
      - "LICENSE"
jobs:
  build:
    name: Build
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        target: [baulk-win64,baulk-arm64]
        include:
          - target: baulk-win64
            short_target: win64
          - target: baulk-arm64
            short_target: arm64
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: compile-baulk
        run: pwsh -NoProfile -NoLogo -ExecutionPolicy unrestricted -File "./script/build.ps1" -Target "${{ matrix.short_target }}"
      - name: Package Release
        if: startsWith(github.ref, 'refs/tags/')
        run: pwsh -NoProfile -NoLogo -ExecutionPolicy unrestricted -File "./script/package.ps1" -Target "${{ matrix.short_target }}"
      - name: Make Appx
        if: startsWith(github.ref, 'refs/tags/')
        run: pwsh -NoProfile -NoLogo -ExecutionPolicy unrestricted -File "./msix/makeAppx.ps1" -Target "${{ matrix.short_target }}"
      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file_glob: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/Baulk-*.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload Setup
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file_glob: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/Baulk*.exe
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload Appx
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file_glob: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/Baulk*.appx
          tag: ${{ github.ref }}
          overwrite: true
