name: Build-VS2022-Preview
on:
  push:
    paths-ignore:
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
      - "docs/**"
      - "**.md"
      - "**.txt"
      - "!CMakeLists.txt"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**.txt"
      - "!CMakeLists.txt"
      - "LICENSE"
jobs:
  build:
    name: Build
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        baulk_target: [baulk-vs2022-win64, baulk-vs2022-win32, baulk-vs2022-arm64]
        include:
          - baulk_target: baulk-vs2022-win64
            short_target: win64
          - baulk_target: baulk-vs2022-win32
            short_target: win32
          - baulk_target: baulk-vs2022-arm64
            short_target: arm64
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: compile-baulk
        run: pwsh -NoProfile -NoLogo -ExecutionPolicy unrestricted -File "./script/build.ps1" -Target "${{ matrix.short_target }}"